################################################################################
## Source: edX
## Series: Foundations of Data Analysis
## Course: 1 Statistics Using R
## Week: Week 4
## Topic: Bivariate Distributions (Categorical Data)
## File: week-04-prelab.R
## Date: 2016-03-14
################################################################################


################################################################################
## Lab 4: Austin City Limits
################################################################################

############################################################
## Primary Research Question:
## For artists age 30 or older, do female artists play different kinds of music
## on Austin City Limits than male artists?
############################################################

######################################################################
## Reflect on the Question
######################################################################

########################################
## Check the Data
########################################

library(SDSFoundations)
acl <- AustinCityLimits

# 1a. How many artists are in the dataset?
dim(acl)[1]

# 1b. How many of the first 10 artists in the dataset were Grammy winners?
first_10 <- acl[1:10, ]
gram_10 <- first_10[which(first_10$Grammy == "Y"), ]
dim(gram_10)[1]

# 1c. What genre was played by the first female artist in the dataset
##      who was over 60 years of age?
females_over_60 <- acl[which(acl$Gender == "F" & acl$Age > 60), ]
females_over_60[1, "Genre"]

########################################
## Check the Variables of Interest
########################################

# 2a. Which variable tells us the kind of music played by each artist?
# Genre

# 2b. What type of variable is this?
# Categorical

# 2c. Which variable tells us whether the lead singer or performer is male or not?
# Gender

# 2d. What type of variable is this?
# Categorical

########################################
## Reflect on the Method
########################################

# 3. We will generate a contingency table of genre and gender 
#       to help us with this analysis. Why?
# The table will show us how many male and female artists played each type 
#   of music.

# 4. We will compare marginal and conditional probabilities to determine
#       if female and male artists tend to play different kinds of music.
#       Why?
# We want to determine if two categorical variables are independent or not.

######################################################################
## Analyze the Data
######################################################################

########################################
## Break Down Your Analysis
########################################

# 1. Create a subset of the data for artists age 30 or older.
older <- acl[acl$Age >= 30, ]

# 2. Create a table to show the marginal distribution for each variable.
genre <- table(older$Genre)
genre
gender <- table(older$Gender)
gender

# 3. Create a contingency table to show the conditional distribution 
#       for gender and genre.
twoway <- table(older$Gender, older$Genre)
twoway

# 4. Make a bar chart to better visualize how many male and female artists
#       played in each genre.
barplot(twoway, legend=T, beside=T)

# 5. Calculate P(A): the probability of each type of music (genre) being played.
prop.table(genre)

# 6. Calculate P(A|B): the probability of each genre, given the artist's gender.
prop.table(twoway, 1)

# 7. Interpret what these probabilities tell us about the relationship
#       between genre and gender.

# 1) How many columns will be present in the table generated by the following
#       line of code?
#       gender <- table(acl$Gender)
# 2

# 2) This code produces a bar chart with both a legend and side-by-side bars
#       for each gender:
#       barplot(twoway, legend=TRUE, beside=TRUE)
#   What would the code look like if we wanted to keep the legend 
#       but stack the bars (instead of set them side-by-side)?
# barplot(twoway, legend=TRUE)

# 3) This line of code will produce four values, one for each genre of music:
#       prop.table(genre)
#   What value should you get if you sum the four values together?
# 1.0

# 4) What does the value "1" refer to in this line of code:
#       prop.table(twoway, 1)
# The number 1 references the first variable (gender) listed in the contingency
#       table code.

# 5) Suppose we ran the following code to find conditional probabilities.
#       What error has caused the prop.table function to not work?
#   acl <- AustinCityLimits
#   View(acl)
#   gender_grammy <- table(acl$Gender, acl$Grammy)
#   prop.table(acl$Gender, acl$Grammy, 1)
#   Error in prop.table(acl$Gender, acl$Grammy, 1) : unused argument (1)
# The prop.table function needs a table as an argument.

########################################
## Conduct Analysis in R
########################################

# 1a. How many male artists are in the 30+ year old artist subset 
#       of the Austin City Limits dataset?
gender
# 77

# 1b. How many female artists are in the 30+ year old artist subset
#       of the Austin City Limits dataset?
# 25

# 2a. To determine the proportion of jazz performers that were male,
#       you would divide ___________ by ____________.
# 7
# 11

# 2b. To determine the proportion of males that performed jazz,
#       you would divide ____________ by ___________.
# 7
# 77

# 3a. Which table should you look at to determine how many artists performed
#       rock/folk/indie music: genre or gender?
# genre

# 3b. How many artists performed rock/folk/indie music?
# 61

# 4a. Which of these lines of code provides the probability that a randomly
#       selected artist from the dataset performed rock/folk/indie music?
prop.table(genre)

# 4b. What is the probability that a randomly selected artist from the dataset
#       performed rock/folk/indie music?
# 0.598

# 5a. Which of these lines of code provides the probability that a randomly
#       selected female artist performed rock/folk/indie music?
prop.table(twoway, 1)

# 5b. What is the probability that a randomly selected female artist performed
#       rock/folk/indie music?
# 0.320

# 6. For genre and gender to be independent, which of the following statements
#       must be true?
# P(rock) = P(rock|female)

######################################################################
## Draw Conclusions
######################################################################

########################################
## Write Your Conclusion
########################################

# The music played on Austin City Limits was grouped into four genres,
# including Country, Jazz, Rock and Singer-Songwriter. We wanted to examine
# only those artists who were age 30 or older. Rock was the most frequently
# played genre, performed by 59.8% of the Austin City Limits artists.
# Among female artists, however, only 32.0% of the artists played Rock music.
# This difference between the marginal and conditional probabilities suggests
# that gender and genre are not independent. This difference was also evident
# in the bar plots, where it was evident that females were more likely 
# to perform in the Singer-Songwriter category than their male counterparts.

################################################################################